// Scenario history copy and field labels. The app has no locale service yet; feature copy follows
// the existing feature-local catalog convention and keeps the component free of ad-hoc wording.

export const SCENARIO_HISTORY_TEXT = {
  heading: "Approval history",
  open: "View approval history",
  loading: "Loading approval history…",
  loadMore: "Load more snapshot inputs",
  denied: "Approval history is unavailable for this scenario.",
  timedOut: "The approval history request timed out.",
  unreadable: "The server returned an unreadable approval history.",
  failed: "Approval history could not be loaded.",
  retry: "Read approval history again",
  noApproval: "No approval event is recorded for this scenario.",
  event: "Approval event",
  approvedInputs: "Saved approval snapshot inputs",
  currentInputs: "This scenario’s saved inputs",
  organizationDefaults: "Organization defaults",
  workingCalendars: "Working calendars",
  workingCalendarDays: "Working calendar days",
  absenceTypes: "Absence types",
  absenceBudgets: "Absence budgets",
  catalogRates: "Catalog rates",
  exchangeRates: "Exchange rates",
  actor: "Actor ID",
  unverified: "Unverified development/test placeholder; not authenticated attribution.",
  updated: "Last updated",
  noRows: "No saved rows.",
} as const;

const FIELD_LABELS: Readonly<Record<string, string>> = {
  start_date: "Start date",
  end_date: "End date",
  working_calendar: "Working calendar",
  full_time_hours_per_week: "Full-time hours per week",
  currency: "Currency",
  target_margin_percent: "Target margin",
  overload_threshold_percent: "Overload threshold",
  source_calendar_id: "Source calendar ID",
  source_location_id: "Source location ID",
  source_absence_type_id: "Source absence type ID",
  source_engagement_type_id: "Source engagement type ID",
  source_rate_id: "Source rate ID",
  source_role_id: "Source role ID",
  source_seniority_id: "Source seniority ID",
  source_vendor_id: "Source vendor ID",
  source_project_id: "Source project ID",
  source_scenario_id: "Source scenario ID",
  standard_hours_per_day: "Standard hours per day",
  week_pattern: "Week pattern",
  day: "Day",
  source: "Source",
  name: "Name",
  country_code: "Country code",
  year: "Year",
  kind: "Kind",
  generates_cost: "Generates cost",
  generates_revenue: "Generates revenue",
  is_statutory_leave: "Statutory leave",
  budget_days: "Budget days",
  unit: "Unit",
  effective_from: "Effective from",
  effective_to: "Effective to",
  default_selling_rate: "Selling rate",
  default_cost_rate: "Cost rate",
  surcharge_percent: "Surcharge",
  includes_surcharge: "Includes surcharge",
  source_scope: "Rate scope",
  source_currency: "Source currency",
  target_currency: "Target currency",
  rate: "Exchange rate",
};

export function scenarioHistoryFieldLabel(field: string): string {
  return FIELD_LABELS[field] ?? field.replace(/_/g, " ").replace(/^./, (letter) => letter.toUpperCase());
}
