"""Budowa lokalnej galerii, planszy przeglądowej i mapy nawigacji."""
from pathlib import Path
import json
from html import escape

root = Path(__file__).resolve().parent.parent
manifest = json.loads((root / 'spec/screen-manifest.json').read_text(encoding='utf-8'))
requirements = {
 'projects':['F-01','F-13'],'overview':['F-10','F-11'],'staffing':['F-04','F-05','F-07'],
 'resource':['F-03','F-04','F-07'],'costs':['F-08'],'cost-detail':['F-08'],
 'tm':['F-06.1'],'fixed':['F-06.2'],'outcome':['F-06.3'],'points':['F-06.4'],
 'compare':['F-09','F-10'],'sensitivity':['F-09'],'assumptions':['F-02','F-05'],
 'calendar':['F-05'],'catalog':['F-03','NF-10'],'versions':['F-12'],'report':['F-11','F-12'],
 'access':['F-13'],'states':['NF-05','NF-07','NF-08'],'create':['F-01','NF-07'],
 'system':['NF-07','NF-08'],'approved':['F-12'],'conflict':['NF-05'],'organization':['F-02','NF-10']}
for s in manifest['desktop']:
 s['requirements']=requirements[s['route']]
(root/'spec/screen-manifest.json').write_text(json.dumps(manifest,indent=2,ensure_ascii=False),encoding='utf-8')
css='''
@import url('assets/fonts.css');
*{box-sizing:border-box}body{font:14px/1.5 Manrope,sans-serif;margin:0;background:#fff;color:#000}a{color:#0047b3;text-decoration:none}a:hover{text-decoration:underline}a:focus-visible,input:focus-visible{outline:3px solid #0066ff;outline-offset:3px}header{padding:42px 48px 28px;border-bottom:1px solid #d7dbe0}header .top{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}header h1{font-size:38px;line-height:1.15;font-weight:600;letter-spacing:-1px;margin:0 0 14px}header p{max-width:800px;color:#555e6b;font-size:14px;margin:0}header .tag{font-size:11px;padding:5px 10px;border-radius:4px;background:#f0f2f5}.accent{width:46px;height:5px;background:#ff5500;margin-bottom:22px}.links{display:flex;gap:18px;font-size:12px}.button{padding:10px 15px;border:1px solid #d7dbe0;border-radius:6px;font-weight:700}.primary{background:#0066ff;color:#fff;border-color:#0066ff}main{padding:28px 48px 48px}.toolbar{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px;color:#555e6b;font-size:12px}.toolbar input{padding:10px 14px;border:1px solid #d7dbe0;border-radius:6px;font:inherit;min-width:260px}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:25px}article{border:1px solid #d7dbe0;border-radius:8px;overflow:hidden;background:white}article .preview{display:block;border-bottom:1px solid #d7dbe0;background:#f0f2f5;height:245px;overflow:hidden}article img{width:100%;height:100%;object-fit:cover;object-position:top}article .caption{padding:15px 18px}article h2{font-size:15px;margin:5px 0 12px}article .meta{display:flex;justify-content:space-between;color:#555e6b;font-size:10px}article .actions{display:flex;gap:18px;font-size:11px}section h2{font-size:24px;font-weight:600;margin-top:38px}.mobile-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:25px}.mobile-grid .preview{height:470px;background:#f0f2f5;text-align:center}.mobile-grid img{width:210px;object-fit:cover;object-position:top;max-width:100%;border-left:1px solid #d7dbe0;border-right:1px solid #d7dbe0}.foot{font-size:12px;color:#555e6b;margin-top:30px;padding-top:20px;border-top:1px solid #d7dbe0}.board{width:1600px}.board header{padding:38px 48px 26px}.board header h1{font-size:40px}.board .grid{grid-template-columns:repeat(3,1fr);gap:20px}.board article .preview{height:295px}.board article .caption{padding:12px 16px}.board article h2{margin:0;font-size:15px}.board article .actions,.board .toolbar{display:none}.board main{padding:28px 48px}.board .overview-note{display:flex;justify-content:space-between;align-items:center;font-size:12px;color:#555e6b;padding-top:24px}.review-grid{grid-template-columns:repeat(2,1fr)}.review-grid article .preview{height:620px}.review-grid article img{object-fit:contain}.review-grid article .caption{padding:8px 14px}
@media(max-width:950px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}header,main{padding:25px}.mobile-grid{grid-template-columns:1fr 1fr}.links{flex-wrap:wrap}}
@media(max-width:600px){.grid,.mobile-grid{grid-template-columns:1fr}header h1{font-size:28px}.toolbar{display:block}.toolbar input{width:100%;margin-top:12px}.links{gap:10px}.board{width:1600px}}
'''
(root/'gallery.css').write_text(css,encoding='utf-8')
def card(s, mobile=False):
 title=s['title']; sid=s.get('id','Mobile'); refs=' / '.join(s.get('requirements',[]))
 return f'''<article data-search="{escape((sid+' '+title+' '+refs).lower())}"><a class="preview" href="{s['image']}" aria-label="Powiększ {escape(title)}"><img src="{s['image']}" alt="{escape(title)} — makieta UI" loading="eager"></a><div class="caption"><div class="meta"><span>{sid}</span><span>{refs}</span></div><h2>{escape(title)}</h2><div class="actions"><a href="index.html#{s['route']}">Otwórz prototyp</a><a href="{s['image']}">Pełna grafika PNG</a></div></div></article>'''
head='''<!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Propozycja UI — Staffing planner</title><link rel="icon" type="image/svg+xml" href="assets/favicon.svg"><link rel="icon" type="image/png" sizes="32x32" href="assets/favicon-32.png"><link rel="apple-touch-icon" sizes="180x180" href="assets/apple-touch-icon.png"><link rel="stylesheet" href="gallery.css"></head>'''
header='''<header><div class="top"><span>Staffing planner / Propozycja interfejsu</span><span class="tag">19.09.2026 · Do przeglądu</span></div><div class="accent"></div><h1>Od planu zespołu do decyzji biznesowej.</h1><p>Jeden kontekst projektu. Cztery modele współpracy. Czytelny wpływ obsady i kosztów na wynik. Pakiet makiet oraz specyfikacja do implementacji z agentami AI i przeglądem człowieka.</p><div class="links" style="margin-top:24px"><a class="button primary" href="index.html">Uruchom prototyp</a><a class="button" href="spec/UI_SPEC.md">Specyfikacja UI</a><a class="button" href="spec/IMPLEMENTATION_HANDOFF.md">Przekazanie SDD / HIL</a><a class="button" href="navigation.svg">Mapa nawigacji</a></div></header>'''
panels=manifest.get('catalog_panels',[])
panel_cards=''.join(f'''<article data-search="{escape((p['id']+' '+p['title']+' UI-15').lower())}"><a class="preview" href="{p['image']}" aria-label="Powiększ {escape(p['title'])} panel"><img src="{p['image']}" alt="{escape(p['title'])} — szczegółowy panel UI-15" loading="eager"></a><div class="caption"><div class="meta"><span>{p['id']}</span><span>UI-15</span></div><h2>{escape(p['title'])}</h2><div class="actions"><a href="index.html#catalog">Otwórz wspólny widok katalogu</a><a href="{p['image']}">Pełna grafika PNG</a></div></div></article>''' for p in panels)
html=head+'<body>'+header+'<main><div class="toolbar"><span>24 widoki desktopowe · 3 warianty mobilne · przykładowe dane</span><label>Szukaj ekranu <input id="search" type="search" placeholder="Nazwa, UI-03 lub F-06"></label></div><div class="grid" id="desktop">'+''.join(card(s) for s in manifest['desktop'])+'</div><section><h2>UI-15 · Panele słowników</h2><p class="catalog-gallery-note">Powiększenia komponentów z ekranu Roles &amp; rates. Nie są to osobne trasy aplikacji.</p><div class="grid" id="catalog-panels">'+panel_cards+'</div></section><section><h2>Przegląd mobilny</h2><div class="mobile-grid">'+''.join(card(s,True) for s in manifest['mobile'])+'</div></section><div class="foot">Propozycja, nie wdrożona aplikacja. Kwoty są demonstracyjne. Źródła i decyzje otwarte: <a href="spec/DESIGN_DECISIONS.md">DESIGN_DECISIONS.md</a>.</div></main><script>document.getElementById("search").addEventListener("input",e=>{const q=e.target.value.toLowerCase();document.querySelectorAll("#desktop article,#catalog-panels article").forEach(a=>a.hidden=!a.dataset.search.includes(q))});</script></body></html>'
(root/'gallery.html').write_text(html,encoding='utf-8')
chosen=['overview','staffing','compare','costs','outcome','versions']
board=head+'<body class="board">'+header.replace('<div class="links"','<div style="display:none" class="links"')+'<main><div class="grid">'+''.join(card(next(s for s in manifest['desktop'] if s['route']==k)) for k in chosen)+'</div><div class="overview-note"><span>Manrope · White / Light steel · Blue / Orange</span><span>24 ekrany + 3 widoki mobile · HTML, PNG i specyfikacja SDD / HIL</span></div></main></body></html>'
(root/'design-overview.html').write_text(board,encoding='utf-8')
for batch in range(6):
 sub=manifest['desktop'][batch*4:(batch+1)*4]
 (root/'tools'/f'review-{batch+1}.html').write_text(head.replace('href="gallery.css"','href="../gallery.css"')+'<body><main><div class="grid review-grid">'+''.join(card({**s,'image':'../'+s['image']}) for s in sub)+'</div></main></body></html>',encoding='utf-8')

nodes=[(40,105,240,85,'Workspace','Projects / UI-01, UI-20'),(350,105,280,85,'Project & scenario','Context + versions'),(710,40,235,75,'Overview','UI-02'),(710,140,235,75,'Staffing & calendars','UI-03, 04, 14'),(710,240,235,75,'Additional costs','UI-05, 06'),(710,340,235,75,'Commercial terms','UI-07, 08, 09, 10'),(710,440,235,75,'Assumptions','UI-13'),(1025,140,250,85,'Compare & simulate','UI-11, 12'),(1025,270,250,85,'Review & approve','UI-16, 22'),(1025,400,250,85,'Report & export','UI-17'),(40,340,240,85,'Organization libraries','Roles, rates, defaults / UI-15, 24'),(350,340,280,85,'Access & resilience','UI-18, 19, 23')]
svg=['<svg xmlns="http://www.w3.org/2000/svg" width="1320" height="630" viewBox="0 0 1320 630"><rect width="1320" height="630" fill="white"/><style>text{font-family:Manrope,Segoe UI,sans-serif}.title{font-size:26px;font-weight:600}.h{font-size:16px;font-weight:600}.sub{font-size:12px;fill:#555e6b}.line{stroke:#0066ff;stroke-width:2;fill:none}</style><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8" fill="none" stroke="#0066ff"/></marker></defs><text x="40" y="45" class="title">Staffing planner / Information architecture</text>']
for d in ['M280 148H350','M630 148H665V78H710','M665 148V178H710','M665 178V278H710','M665 278V378H710','M665 378V478H710','M945 78H988V182H1025','M1150 225V270','M1150 355V400','M160 340V230H490V190','M490 190V340']:
 svg.append(f'<path d="{d}" class="line" marker-end="url(#arrow)"/>')
for x,y,w,h,title,sub in nodes:
 svg.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="7" fill="#f0f2f5" stroke="#d7dbe0"/><text x="{x+18}" y="{y+31}" class="h">{escape(title)}</text><text x="{x+18}" y="{y+55}" class="sub">{escape(sub)}</text>')
svg.append('<text x="40" y="568" class="sub">Product flow: plan → compare → review → approved snapshot. Development gates remain in the existing SDD / HIL process.</text><text x="40" y="598" class="sub">Proposal v1.0 • 19 September 2026 • Routes and components require human scope approval before production implementation.</text></svg>')
(root/'navigation.svg').write_text(''.join(svg),encoding='utf-8')
print('Gallery, overview board and navigation map generated.')
